apiVersion: aws.kraken-iac.eoinfennessy.com/v1alpha1
kind: EC2Instance
metadata:
  name: ec2instance-b
spec:
  imageID:
    valueFrom:
      configMap:
        name: configmap-a
        key: imageID
  instanceType:
    valueFrom:
      krakenResource:
        kind: ec2instance
        name: ec2instance-a
        path: instances.0.InstanceType
  maxCount:
    valueFrom:
      configMap:
        name: configmap-a
        key: maxCount
  minCount:
    value: 1