apiVersion: aws.kraken-iac.eoinfennessy.com/v1alpha1
kind: EC2Instance
metadata:
  name: ec2instance-a
spec:
  imageID:
    valueFrom:
      configMap:
        name: configmap-a
        key: imageID
  instanceType:
    value: "t2.nano"
  maxCount:
    value: 1
  minCount:
    value: 1